/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AccompagnementContinuRouteImport } from './routes/accompagnement-continu'
import { Route as ApplicationMetierSurMesureRouteImport } from './routes/application-metier-sur-mesure'
import { Route as AuditDeProcessRouteImport } from './routes/audit-de-process'
import { Route as AutomatiserUnReportingRouteImport } from './routes/automatiser-un-reporting'
import { Route as DigitalisationDesProcessusRouteImport } from './routes/digitalisation-des-processus'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as ReprendreUnOutilInterneRouteImport } from './routes/reprendre-un-outil-interne'
import { Route as SynchroniserSesOutilsRouteImport } from './routes/synchroniser-ses-outils'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TransformationDigitalePmeRouteImport } from './routes/transformation-digitale-pme'
import { Route as CasClientsIndexRouteImport } from './routes/cas-clients.index'
import { Route as CasClientsMedicheckRouteImport } from './routes/cas-clients.medicheck'
import { Route as CasClientsPurposeRecruitingRouteImport } from './routes/cas-clients.purpose-recruiting'
import { Route as CasClientsTeachForBelgiumRouteImport } from './routes/cas-clients.teach-for-belgium'
import { Route as CasClientsWwfRouteImport } from './routes/cas-clients.wwf'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnBespokeSoftwareDevelopmentRouteImport } from './routes/en/bespoke-software-development'
import { Route as EnCaseStudiesRouteImport } from './routes/en/case-studies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AccompagnementContinuRoute = AccompagnementContinuRouteImport.update({
  id: '/accompagnement-continu',
  path: '/accompagnement-continu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationMetierSurMesureRoute =
  ApplicationMetierSurMesureRouteImport.update({
    id: '/application-metier-sur-mesure',
    path: '/application-metier-sur-mesure',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuditDeProcessRoute = AuditDeProcessRouteImport.update({
  id: '/audit-de-process',
  path: '/audit-de-process',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatiserUnReportingRoute = AutomatiserUnReportingRouteImport.update({
  id: '/automatiser-un-reporting',
  path: '/automatiser-un-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalisationDesProcessusRoute =
  DigitalisationDesProcessusRouteImport.update({
    id: '/digitalisation-des-processus',
    path: '/digitalisation-des-processus',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReprendreUnOutilInterneRoute = ReprendreUnOutilInterneRouteImport.update({
  id: '/reprendre-un-outil-interne',
  path: '/reprendre-un-outil-interne',
  getParentRoute: () => rootRouteImport,
} as any)
const SynchroniserSesOutilsRoute = SynchroniserSesOutilsRouteImport.update({
  id: '/synchroniser-ses-outils',
  path: '/synchroniser-ses-outils',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationDigitalePmeRoute =
  TransformationDigitalePmeRouteImport.update({
    id: '/transformation-digitale-pme',
    path: '/transformation-digitale-pme',
    getParentRoute: () => rootRouteImport,
  } as any)
const CasClientsIndexRoute = CasClientsIndexRouteImport.update({
  id: '/cas-clients/',
  path: '/cas-clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasClientsMedicheckRoute = CasClientsMedicheckRouteImport.update({
  id: '/cas-clients/medicheck',
  path: '/cas-clients/medicheck',
  getParentRoute: () => rootRouteImport,
} as any)
const CasClientsPurposeRecruitingRoute =
  CasClientsPurposeRecruitingRouteImport.update({
    id: '/cas-clients/purpose-recruiting',
    path: '/cas-clients/purpose-recruiting',
    getParentRoute: () => rootRouteImport,
  } as any)
const CasClientsTeachForBelgiumRoute =
  CasClientsTeachForBelgiumRouteImport.update({
    id: '/cas-clients/teach-for-belgium',
    path: '/cas-clients/teach-for-belgium',
    getParentRoute: () => rootRouteImport,
  } as any)
const CasClientsWwfRoute = CasClientsWwfRouteImport.update({
  id: '/cas-clients/wwf',
  path: '/cas-clients/wwf',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnBespokeSoftwareDevelopmentRoute =
  EnBespokeSoftwareDevelopmentRouteImport.update({
    id: '/bespoke-software-development',
    path: '/bespoke-software-development',
    getParentRoute: () => EnRouteRoute,
  } as any)
const EnCaseStudiesRoute = EnCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => EnRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/accompagnement-continu': typeof AccompagnementContinuRoute
  '/application-metier-sur-mesure': typeof ApplicationMetierSurMesureRoute
  '/audit-de-process': typeof AuditDeProcessRoute
  '/automatiser-un-reporting': typeof AutomatiserUnReportingRoute
  '/digitalisation-des-processus': typeof DigitalisationDesProcessusRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/reprendre-un-outil-interne': typeof ReprendreUnOutilInterneRoute
  '/synchroniser-ses-outils': typeof SynchroniserSesOutilsRoute
  '/tarifs': typeof TarifsRoute
  '/transformation-digitale-pme': typeof TransformationDigitalePmeRoute
  '/cas-clients/medicheck': typeof CasClientsMedicheckRoute
  '/cas-clients/purpose-recruiting': typeof CasClientsPurposeRecruitingRoute
  '/cas-clients/teach-for-belgium': typeof CasClientsTeachForBelgiumRoute
  '/cas-clients/wwf': typeof CasClientsWwfRoute
  '/en/about': typeof EnAboutRoute
  '/en/bespoke-software-development': typeof EnBespokeSoftwareDevelopmentRoute
  '/en/case-studies': typeof EnCaseStudiesRoute
  '/cas-clients/': typeof CasClientsIndexRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/accompagnement-continu': typeof AccompagnementContinuRoute
  '/application-metier-sur-mesure': typeof ApplicationMetierSurMesureRoute
  '/audit-de-process': typeof AuditDeProcessRoute
  '/automatiser-un-reporting': typeof AutomatiserUnReportingRoute
  '/digitalisation-des-processus': typeof DigitalisationDesProcessusRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/reprendre-un-outil-interne': typeof ReprendreUnOutilInterneRoute
  '/synchroniser-ses-outils': typeof SynchroniserSesOutilsRoute
  '/tarifs': typeof TarifsRoute
  '/transformation-digitale-pme': typeof TransformationDigitalePmeRoute
  '/cas-clients/medicheck': typeof CasClientsMedicheckRoute
  '/cas-clients/purpose-recruiting': typeof CasClientsPurposeRecruitingRoute
  '/cas-clients/teach-for-belgium': typeof CasClientsTeachForBelgiumRoute
  '/cas-clients/wwf': typeof CasClientsWwfRoute
  '/en/about': typeof EnAboutRoute
  '/en/bespoke-software-development': typeof EnBespokeSoftwareDevelopmentRoute
  '/en/case-studies': typeof EnCaseStudiesRoute
  '/cas-clients': typeof CasClientsIndexRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/accompagnement-continu': typeof AccompagnementContinuRoute
  '/application-metier-sur-mesure': typeof ApplicationMetierSurMesureRoute
  '/audit-de-process': typeof AuditDeProcessRoute
  '/automatiser-un-reporting': typeof AutomatiserUnReportingRoute
  '/digitalisation-des-processus': typeof DigitalisationDesProcessusRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/reprendre-un-outil-interne': typeof ReprendreUnOutilInterneRoute
  '/synchroniser-ses-outils': typeof SynchroniserSesOutilsRoute
  '/tarifs': typeof TarifsRoute
  '/transformation-digitale-pme': typeof TransformationDigitalePmeRoute
  '/cas-clients/medicheck': typeof CasClientsMedicheckRoute
  '/cas-clients/purpose-recruiting': typeof CasClientsPurposeRecruitingRoute
  '/cas-clients/teach-for-belgium': typeof CasClientsTeachForBelgiumRoute
  '/cas-clients/wwf': typeof CasClientsWwfRoute
  '/en/about': typeof EnAboutRoute
  '/en/bespoke-software-development': typeof EnBespokeSoftwareDevelopmentRoute
  '/en/case-studies': typeof EnCaseStudiesRoute
  '/cas-clients/': typeof CasClientsIndexRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/a-propos'
    | '/accompagnement-continu'
    | '/application-metier-sur-mesure'
    | '/audit-de-process'
    | '/automatiser-un-reporting'
    | '/digitalisation-des-processus'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/reprendre-un-outil-interne'
    | '/synchroniser-ses-outils'
    | '/tarifs'
    | '/transformation-digitale-pme'
    | '/cas-clients/medicheck'
    | '/cas-clients/purpose-recruiting'
    | '/cas-clients/teach-for-belgium'
    | '/cas-clients/wwf'
    | '/en/about'
    | '/en/bespoke-software-development'
    | '/en/case-studies'
    | '/cas-clients/'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/accompagnement-continu'
    | '/application-metier-sur-mesure'
    | '/audit-de-process'
    | '/automatiser-un-reporting'
    | '/digitalisation-des-processus'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/reprendre-un-outil-interne'
    | '/synchroniser-ses-outils'
    | '/tarifs'
    | '/transformation-digitale-pme'
    | '/cas-clients/medicheck'
    | '/cas-clients/purpose-recruiting'
    | '/cas-clients/teach-for-belgium'
    | '/cas-clients/wwf'
    | '/en/about'
    | '/en/bespoke-software-development'
    | '/en/case-studies'
    | '/cas-clients'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/a-propos'
    | '/accompagnement-continu'
    | '/application-metier-sur-mesure'
    | '/audit-de-process'
    | '/automatiser-un-reporting'
    | '/digitalisation-des-processus'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/reprendre-un-outil-interne'
    | '/synchroniser-ses-outils'
    | '/tarifs'
    | '/transformation-digitale-pme'
    | '/cas-clients/medicheck'
    | '/cas-clients/purpose-recruiting'
    | '/cas-clients/teach-for-belgium'
    | '/cas-clients/wwf'
    | '/en/about'
    | '/en/bespoke-software-development'
    | '/en/case-studies'
    | '/cas-clients/'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRouteRoute: typeof EnRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AccompagnementContinuRoute: typeof AccompagnementContinuRoute
  ApplicationMetierSurMesureRoute: typeof ApplicationMetierSurMesureRoute
  AuditDeProcessRoute: typeof AuditDeProcessRoute
  AutomatiserUnReportingRoute: typeof AutomatiserUnReportingRoute
  DigitalisationDesProcessusRoute: typeof DigitalisationDesProcessusRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  ReprendreUnOutilInterneRoute: typeof ReprendreUnOutilInterneRoute
  SynchroniserSesOutilsRoute: typeof SynchroniserSesOutilsRoute
  TarifsRoute: typeof TarifsRoute
  TransformationDigitalePmeRoute: typeof TransformationDigitalePmeRoute
  CasClientsMedicheckRoute: typeof CasClientsMedicheckRoute
  CasClientsPurposeRecruitingRoute: typeof CasClientsPurposeRecruitingRoute
  CasClientsTeachForBelgiumRoute: typeof CasClientsTeachForBelgiumRoute
  CasClientsWwfRoute: typeof CasClientsWwfRoute
  CasClientsIndexRoute: typeof CasClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accompagnement-continu': {
      id: '/accompagnement-continu'
      path: '/accompagnement-continu'
      fullPath: '/accompagnement-continu'
      preLoaderRoute: typeof AccompagnementContinuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-metier-sur-mesure': {
      id: '/application-metier-sur-mesure'
      path: '/application-metier-sur-mesure'
      fullPath: '/application-metier-sur-mesure'
      preLoaderRoute: typeof ApplicationMetierSurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-de-process': {
      id: '/audit-de-process'
      path: '/audit-de-process'
      fullPath: '/audit-de-process'
      preLoaderRoute: typeof AuditDeProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatiser-un-reporting': {
      id: '/automatiser-un-reporting'
      path: '/automatiser-un-reporting'
      fullPath: '/automatiser-un-reporting'
      preLoaderRoute: typeof AutomatiserUnReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitalisation-des-processus': {
      id: '/digitalisation-des-processus'
      path: '/digitalisation-des-processus'
      fullPath: '/digitalisation-des-processus'
      preLoaderRoute: typeof DigitalisationDesProcessusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reprendre-un-outil-interne': {
      id: '/reprendre-un-outil-interne'
      path: '/reprendre-un-outil-interne'
      fullPath: '/reprendre-un-outil-interne'
      preLoaderRoute: typeof ReprendreUnOutilInterneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synchroniser-ses-outils': {
      id: '/synchroniser-ses-outils'
      path: '/synchroniser-ses-outils'
      fullPath: '/synchroniser-ses-outils'
      preLoaderRoute: typeof SynchroniserSesOutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformation-digitale-pme': {
      id: '/transformation-digitale-pme'
      path: '/transformation-digitale-pme'
      fullPath: '/transformation-digitale-pme'
      preLoaderRoute: typeof TransformationDigitalePmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-clients/': {
      id: '/cas-clients/'
      path: '/cas-clients'
      fullPath: '/cas-clients/'
      preLoaderRoute: typeof CasClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-clients/medicheck': {
      id: '/cas-clients/medicheck'
      path: '/cas-clients/medicheck'
      fullPath: '/cas-clients/medicheck'
      preLoaderRoute: typeof CasClientsMedicheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-clients/purpose-recruiting': {
      id: '/cas-clients/purpose-recruiting'
      path: '/cas-clients/purpose-recruiting'
      fullPath: '/cas-clients/purpose-recruiting'
      preLoaderRoute: typeof CasClientsPurposeRecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-clients/teach-for-belgium': {
      id: '/cas-clients/teach-for-belgium'
      path: '/cas-clients/teach-for-belgium'
      fullPath: '/cas-clients/teach-for-belgium'
      preLoaderRoute: typeof CasClientsTeachForBelgiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-clients/wwf': {
      id: '/cas-clients/wwf'
      path: '/cas-clients/wwf'
      fullPath: '/cas-clients/wwf'
      preLoaderRoute: typeof CasClientsWwfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/bespoke-software-development': {
      id: '/en/bespoke-software-development'
      path: '/bespoke-software-development'
      fullPath: '/en/bespoke-software-development'
      preLoaderRoute: typeof EnBespokeSoftwareDevelopmentRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/case-studies': {
      id: '/en/case-studies'
      path: '/case-studies'
      fullPath: '/en/case-studies'
      preLoaderRoute: typeof EnCaseStudiesRouteImport
      parentRoute: typeof EnRouteRoute
    }
  }
}

interface EnRouteRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnBespokeSoftwareDevelopmentRoute: typeof EnBespokeSoftwareDevelopmentRoute
  EnCaseStudiesRoute: typeof EnCaseStudiesRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnBespokeSoftwareDevelopmentRoute: EnBespokeSoftwareDevelopmentRoute,
  EnCaseStudiesRoute: EnCaseStudiesRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRouteRoute: EnRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AccompagnementContinuRoute: AccompagnementContinuRoute,
  ApplicationMetierSurMesureRoute: ApplicationMetierSurMesureRoute,
  AuditDeProcessRoute: AuditDeProcessRoute,
  AutomatiserUnReportingRoute: AutomatiserUnReportingRoute,
  DigitalisationDesProcessusRoute: DigitalisationDesProcessusRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  ReprendreUnOutilInterneRoute: ReprendreUnOutilInterneRoute,
  SynchroniserSesOutilsRoute: SynchroniserSesOutilsRoute,
  TarifsRoute: TarifsRoute,
  TransformationDigitalePmeRoute: TransformationDigitalePmeRoute,
  CasClientsMedicheckRoute: CasClientsMedicheckRoute,
  CasClientsPurposeRecruitingRoute: CasClientsPurposeRecruitingRoute,
  CasClientsTeachForBelgiumRoute: CasClientsTeachForBelgiumRoute,
  CasClientsWwfRoute: CasClientsWwfRoute,
  CasClientsIndexRoute: CasClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
